project_id = "udaudwkblphataokaexq"

[functions.create-yoco-checkout]
verify_jwt = false

[functions.yoco-webhook]
verify_jwt = false

[functions.register-yoco-webhook]
verify_jwt = false

[functions.create-book-checkout]
verify_jwt = false

[functions.generate-book-pdf]
verify_jwt = false
